/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.client.view;

import com.java.client.Main;
import com.java.config.LookConfig;
import com.java.model.dao.ChucvuDAO;
import com.java.model.dao.ChuyenmonDAO;
import com.java.model.dao.MucLuongDAO;
import com.java.model.dao.NhanvienDAO;
import com.java.model.dao.PhieuLuongDAO;
import com.java.model.dao.PhongbanDAO;
import com.java.model.dao.QuequanDAO;
import com.java.model.dao.TrinhDoDAO;
import com.java.model.dao.TrinhDoNNDAO;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author macos
 */
public class LoadScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoadScreen
     */
    public LoadScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Progress = new javax.swing.JProgressBar();
        LoadMess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Loading Screen");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(0, 173, 233));
        Title.setForeground(new java.awt.Color(0, 173, 233));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome To Crystal Company Application");

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(73, 73, 73))
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 90));

        jPanel1.setBackground(new java.awt.Color(0, 191, 233));

        LoadMess.setForeground(new java.awt.Color(255, 255, 255));
        LoadMess.setText("Loading");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Progress, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(LoadMess)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(Progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoadMess)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 400, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void callRun() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (LookConfig.LookAndFeel.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        this.setVisible(true);
        //</editor-fold>
        this.Progress.setValue(0);
        Thread t1 = new Thread(()->{
            QuanLiNhanSu.danhSachChuyenMon = ChuyenmonDAO.getDanhSachCM();
            this.Progress.setValue(this.Progress.getValue()+10);
            this.LoadMess.setText("Loading Technique List");
            QuanLiNhanSu.Quequan = QuequanDAO.getAllTinh();
            this.Progress.setValue(this.Progress.getValue()+10);
            this.LoadMess.setText("Loading City List");
            LapPhieuLuong.phieuLuong = PhieuLuongDAO.getDanhSachPhieuLuong();
            QuanLiNhanSu.danhSachtrinhDoNN = TrinhDoNNDAO.getListTrinhDoNN();
            this.Progress.setValue(this.Progress.getValue()+10);
            this.LoadMess.setText("Loading Foreign Language Level"); 
            
        });
        Thread t2 = new Thread(()->{
            this.LoadMess.setText("Loading Salary");
            QuanLiLuong.danhSachMucLuong = MucLuongDAO.getAllMucLuong();
            this.Progress.setValue(this.Progress.getValue() + 10);
            QuanLiNhanSu.danhSachPhongBan = PhongbanDAO.getDanhSachPhongBan();
            this.Progress.setValue(this.Progress.getValue()+10);
            this.LoadMess.setText("Loading Department List");
            QuanLiNhanSu.danhSachNhanVien = NhanvienDAO.getAllNhanvien();
            this.Progress.setValue(this.Progress.getValue()+10);
            this.LoadMess.setText("Loading Employee List");
        });
        t1.start();
        t2.start();
        try {
            t2.join();
            this.dispose();
            DangNhap.callRun();
        } catch (InterruptedException ex) {
            Logger.getLogger(LoadScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void LoadingController(){
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoadMess;
    private javax.swing.JProgressBar Progress;
    private javax.swing.JPanel Title;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
