/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.client.view;

import com.java.client.controller.DateController;
import com.java.model.Chucvu;
import com.java.model.Chuyenmon;
import com.java.model.Huyen;
import com.java.model.Nhanvien;
import com.java.model.Phongban;
import com.java.model.TDHV;
import com.java.model.Tinh;
import com.java.model.TrinhDoNN;
import com.java.model.dao.QuequanDAO;
import java.util.Set;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 8
 */
public class Nhap_Sua_TTNV extends javax.swing.JFrame {

    private Nhanvien nv;
    public static Nhap_Sua_TTNV obj = null;
    /**
     * Creates new form Nhap_Sua_TTNV
     */
    public Nhap_Sua_TTNV() {
        initComponents();
        nv = new Nhanvien();
        Set<String> danhSachMa = QuanLiNhanSu.danhSachNhanVien.keySet();
        int max = 0;
        for (String maNV : danhSachMa) {
            if (maNV.contains("NV")) {
                int ma = Integer.parseInt(maNV.substring(2));
                if (max < ma) {
                    max = ma;
                }
            }
        }
        nv.setMaNv("NV" + String.format("%03d", max + 1));
    }

    public Nhap_Sua_TTNV(Nhanvien nv) {
        initComponents();
        this.nv = nv;
        this.txtname.setText(nv.getTenNv());
        this.txtgioitinh.setSelectedItem(nv.isPhai() ? "Male" : "Female");
        this.txtdiachi.setText(nv.getDc());
        this.txttinh.setSelectedItem(QuanLiNhanSu.Quequan.get(nv.getMaT()));
        this.txtquanhuyen.setSelectedItem(QuanLiNhanSu.Quequan.get(nv.getMaT()).getHuyen(nv.getMaH()));
        this.txtngaysinh.setText(nv.getNgSinh());
        this.txtchucvu.setSelectedItem(QuanLiNhanSu.danhSachPhongBan.get(nv.getMaPb()).getChucvu(nv.getMaCv()));
        this.txtphongbancongtac.setSelectedItem(QuanLiNhanSu.danhSachPhongBan.get(nv.getMaPb()));
        this.txttrinhdohocvan.setSelectedItem(QuanLiNhanSu.danhSachChuyenMon.get(nv.getMaCM()).getTDHV(nv.getMaTDHV()));
        this.txtchuyenmon.setSelectedItem(QuanLiNhanSu.danhSachChuyenMon.get(nv.getMaCM()));
        this.txtmatkhau.setEnabled(false);
        this.txtemail.setText(nv.getEmail());
        this.txtdienthoai.setText(nv.getDienThoai());
        this.txttrinhdongoaingu.setSelectedItem(QuanLiNhanSu.danhSachtrinhDoNN.get(nv.getMaTDNN()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtgioitinh = new javax.swing.JComboBox<>();
        txtdiachi = new javax.swing.JTextField();
        txtquanhuyen = new javax.swing.JComboBox<>();
        txttinh = new javax.swing.JComboBox<>();
        txtngaysinh = new javax.swing.JTextField();
        txtchucvu = new javax.swing.JComboBox<>();
        txtphongbancongtac = new javax.swing.JComboBox<>();
        txtemail = new javax.swing.JTextField();
        txtdienthoai = new javax.swing.JTextField();
        txttrinhdohocvan = new javax.swing.JComboBox<>();
        txtchuyenmon = new javax.swing.JComboBox<>();
        txttrinhdongoaingu = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        btback = new javax.swing.JButton();
        btnext = new javax.swing.JButton();
        btcancel = new javax.swing.JButton();
        txtmatkhau = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter Employee Information");

        jLabel2.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        jLabel2.setText("Full name:");

        jLabel3.setText("Sex:");

        jLabel4.setText("Address:");

        jLabel5.setText("District:");

        jLabel6.setText("Province/ City:");

        jLabel7.setText("Birthday: (dd/mm/yy)");

        jLabel9.setText("Position:");

        jLabel10.setText("Department:");

        jLabel11.setText("Phone");

        jLabel12.setText("Email:");

        jLabel13.setText("Password:");

        jLabel14.setText("Academic Level:");

        jLabel15.setText("Technique:");

        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnameFocusLost(evt);
            }
        });

        txtgioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        txtgioitinh.setName(""); // NOI18N
        txtgioitinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtgioitinhFocusLost(evt);
            }
        });
        txtgioitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgioitinhActionPerformed(evt);
            }
        });

        txtdiachi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdiachiFocusLost(evt);
            }
        });

        txtquanhuyen.setModel(createComboListMaHuyen());
        txtquanhuyen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtquanhuyenItemStateChanged(evt);
            }
        });

        txttinh.setModel(createComboListTinh());
        txttinh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txttinhItemStateChanged(evt);
            }
        });

        txtngaysinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtngaysinhFocusLost(evt);
            }
        });

        txtchucvu.setModel(this.createListChucVu());
        txtchucvu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtchucvuItemStateChanged(evt);
            }
        });

        txtphongbancongtac.setModel(createListPhongBan());
        txtphongbancongtac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtphongbancongtacItemStateChanged(evt);
            }
        });

        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });

        txtdienthoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdienthoaiFocusLost(evt);
            }
        });

        txttrinhdohocvan.setModel(this.createListTDHV());
        txttrinhdohocvan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txttrinhdohocvanItemStateChanged(evt);
            }
        });

        txtchuyenmon.setModel(this.createListChuyenMon());
        txtchuyenmon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtchuyenmonItemStateChanged(evt);
            }
        });

        txttrinhdongoaingu.setModel(this.createListTrinhDoNN());
        txttrinhdongoaingu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txttrinhdongoainguItemStateChanged(evt);
            }
        });
        txttrinhdongoaingu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttrinhdongoainguFocusLost(evt);
            }
        });

        jLabel16.setText("English Level:");

        btback.setText("Back");
        btback.setEnabled(false);
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });

        btnext.setText("Next");
        btnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnextActionPerformed(evt);
            }
        });

        btcancel.setText("Cancel");
        btcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelActionPerformed(evt);
            }
        });

        txtmatkhau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmatkhauFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtquanhuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txttinh, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtphongbancongtac, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtdienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txttrinhdohocvan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btback)
                        .addGap(6, 6, 6)
                        .addComponent(btnext)
                        .addGap(6, 6, 6)
                        .addComponent(btcancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(txttrinhdongoaingu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(txtchuyenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(txtgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(txtquanhuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(txttinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtphongbancongtac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtdienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttrinhdohocvan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtchuyenmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txttrinhdongoaingu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btback)
                    .addComponent(btnext)
                    .addComponent(btcancel)))
        );

        jLabel7.getAccessibleContext().setAccessibleName("Ngày sinh (dd/mmm/yy):");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtgioitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgioitinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgioitinhActionPerformed

    private void btcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelActionPerformed
        int choose = JOptionPane.showConfirmDialog(rootPane, "Do you want to reset this form", "Reset all value of form", JOptionPane.YES_NO_OPTION);
        if (choose == 0) {
            Nhap_Sua_TTNV.callrun();
            this.dispose();
        }
    }//GEN-LAST:event_btcancelActionPerformed

    private void btnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnextActionPerformed
        this.setVisible(false);
        this.txttrinhdongoainguItemStateChanged(null);
        NoiCongTac.callRun(nv);
    }//GEN-LAST:event_btnextActionPerformed

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed

    }//GEN-LAST:event_btbackActionPerformed

    private void txtngaysinhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtngaysinhFocusLost
        /*RegEx Contributor: Alok Chaudhary
         Read more: https://stackoverflow.com/questions/15491894/regex-to-validate-date-format-dd-mm-yyyy
         */
        if (this.txtngaysinh.getText().matches("^(?:(?:31(\\/|-|\\.)"
                + "(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)"
                + "(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|"
                + "^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|"
                + "[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))"
                + "$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))"
                + "\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$")) {
            nv.setNgSinh(DateController.parseStringtoDate(this.txtngaysinh.getText()));
        } else {
            txtngaysinh.setToolTipText("Format: dd/mm/yyyy");
            txtngaysinh.requestFocus();
        }
    }//GEN-LAST:event_txtngaysinhFocusLost

    private void txtnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusLost
        // TODO add your handling code here:

        nv.setTenNv(this.txtname.getText());

        //test 
        System.out.println(nv.getMaNv());
        System.out.println(nv.getTenNv());
    }//GEN-LAST:event_txtnameFocusLost

    private void txtgioitinhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtgioitinhFocusLost
        String slt = ((String) this.txtgioitinh.getSelectedItem());
        if (slt.equals("Male")) {
            nv.setPhai(true);
        } else {
            nv.setPhai(false);
        }
        System.out.println(nv.isPhai());
    }//GEN-LAST:event_txtgioitinhFocusLost

    private void txtdiachiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdiachiFocusLost
        nv.setDc(this.txtdiachi.getText());
        System.out.println(nv.getDc());
    }//GEN-LAST:event_txtdiachiFocusLost

    private void txtdienthoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdienthoaiFocusLost
        // TODO add your handling code here:
        nv.setDienThoai(this.txtdienthoai.getText());
    }//GEN-LAST:event_txtdienthoaiFocusLost

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
        // TODO add your handling code here:
        nv.setEmail(this.txtemail.getText());
        System.out.println(nv.getEmail());
    }//GEN-LAST:event_txtemailFocusLost

    private void txtmatkhauFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmatkhauFocusLost
        // TODO add your handling code here:
        nv.setPassword(this.txtmatkhau.getText());
    }//GEN-LAST:event_txtmatkhauFocusLost

    private void txttinhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txttinhItemStateChanged
        this.txtquanhuyen.setModel(createComboListMaHuyen());
        nv.setMaT(((Tinh) this.txttinh.getSelectedItem()).getMaTinh());
        nv.setMaH(((Huyen) this.txtquanhuyen.getSelectedItem()).getMaHuyen());
        System.out.println(nv.getMaT());
    }//GEN-LAST:event_txttinhItemStateChanged

    private void txtphongbancongtacItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtphongbancongtacItemStateChanged
        // TODO add your handling code here:
        this.txtchucvu.setModel(this.createListChucVu());
        nv.setMaPb(((Phongban) this.txtphongbancongtac.getSelectedItem()).getMaPB());
        nv.setMaCv(((Chucvu) this.txtchucvu.getSelectedItem()).getMaCV());
        System.out.println(nv.getMaPb());
    }//GEN-LAST:event_txtphongbancongtacItemStateChanged

    private void txtchuyenmonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtchuyenmonItemStateChanged
        // TODO add your handling code here:
        // TODO add your handling code here:
        //Instance of String then not casting anything
            this.txttrinhdohocvan.setModel(this.createListTDHV());
            String value = ((Chuyenmon) this.txtchuyenmon.getSelectedItem()).getMaCM();
            nv.setMaCM(value);
            nv.setMaTDHV(((TDHV) this.txttrinhdohocvan.getSelectedItem()).getMaTDHV());
            System.out.println(nv.getMaCM());
    }//GEN-LAST:event_txtchuyenmonItemStateChanged

    private void txttrinhdongoainguItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txttrinhdongoainguItemStateChanged
        // TODO add your handling code here:
        String value = ((TrinhDoNN) this.txttrinhdongoaingu.getSelectedItem()).getMaTDNN();
        nv.setMaTDNN(value);
        System.out.println(nv.getMaTDNN());
    }//GEN-LAST:event_txttrinhdongoainguItemStateChanged

    private void txttrinhdongoainguFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttrinhdongoainguFocusLost
        this.txtchuyenmonItemStateChanged(null);
    }//GEN-LAST:event_txttrinhdongoainguFocusLost

    private void txttrinhdohocvanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txttrinhdohocvanItemStateChanged
        // TODO add your handling code here:
        if (!(this.txttrinhdohocvan.getSelectedItem() instanceof String)) {
            String value = ((TDHV) this.txttrinhdohocvan.getSelectedItem()).getMaTDHV();
            nv.setMaTDHV(value);
            System.out.println(nv.getMaTDHV());
        }
    }//GEN-LAST:event_txttrinhdohocvanItemStateChanged

    private void txtchucvuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtchucvuItemStateChanged
        // TODO add your handling code here:
        nv.setMaCv(((Chucvu) this.txtchucvu.getSelectedItem()).getMaCV());
    }//GEN-LAST:event_txtchucvuItemStateChanged

    private void txtquanhuyenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtquanhuyenItemStateChanged
        // TODO add your handling code here:
        nv.setMaH(((Huyen) this.txtquanhuyen.getSelectedItem()).getMaHuyen());
    }//GEN-LAST:event_txtquanhuyenItemStateChanged

    private DefaultComboBoxModel createComboListMaHuyen() {
        Vector<Huyen> list = new Vector<>();
        String value;
        try {
            value = ((Tinh) this.txttinh.getSelectedItem()).getMaTinh();
        } catch (NullPointerException ex) {
            String[] a = {"Select city first"};
            return new javax.swing.DefaultComboBoxModel<>(a);
        }
        System.out.println(value);
        QuanLiNhanSu.Quequan = QuequanDAO.getAllTinh();
        QuanLiNhanSu.Quequan.get(value).getHuyen().values()
                .forEach(x -> list.addElement(x));
        return new javax.swing.DefaultComboBoxModel(list);
    }

    private DefaultComboBoxModel createComboListTinh() {
        Vector<Tinh> list = new Vector<>();
        QuanLiNhanSu.Quequan.values().stream().forEach(x -> list.addElement(x));
        DefaultComboBoxModel obj = new javax.swing.DefaultComboBoxModel<>(list);
        obj.setSelectedItem("Select a option");
        return obj;
    }

    private DefaultComboBoxModel createListPhongBan() {
        Vector<Phongban> list = new Vector<>();
        QuanLiNhanSu.danhSachPhongBan.values().stream().forEach(x -> list.addElement(x));
        DefaultComboBoxModel obj = new javax.swing.DefaultComboBoxModel<>(list);
        obj.setSelectedItem("Select a Department");
        return obj;
    }

    private DefaultComboBoxModel createListChucVu() {
        Vector<Chucvu> list = new Vector<>();
        String value;
        try {
            value = ((Phongban) this.txtphongbancongtac.getSelectedItem()).getMaPB();
        } catch (NullPointerException ex) {
            String[] a = {"Select Department First"};
            return new javax.swing.DefaultComboBoxModel<>(a);
        }
        System.out.println(value);
        QuanLiNhanSu.danhSachPhongBan.get(value).getDanhSachChucVu().values()
                .stream()
                .forEach(x -> list.addElement(x));
        return new javax.swing.DefaultComboBoxModel(list);
    }

    private DefaultComboBoxModel createListChuyenMon() {
        Vector<Chuyenmon> list = new Vector<>();
        QuanLiNhanSu.danhSachChuyenMon.values().stream()
                .forEach(x -> list.addElement(x));
        DefaultComboBoxModel obj = new DefaultComboBoxModel(list);
        obj.setSelectedItem("Select a Technique");
        return obj;
    }

    private DefaultComboBoxModel createListTDHV() {
        Vector<TDHV> list = new Vector<>();
        String value;
        try {
            value = ((Chuyenmon) this.txtchuyenmon.getSelectedItem()).getMaCM();
        } catch (NullPointerException ex) {
            String[] a = {"Select Department First"};
            return new javax.swing.DefaultComboBoxModel<>(a);
        }
        QuanLiNhanSu.danhSachChuyenMon.get(value).getTDHV().values()
                .stream()
                .forEach(x -> list.addElement(x));
        return new javax.swing.DefaultComboBoxModel<>(list);
    }

    private DefaultComboBoxModel createListTrinhDoNN() {
        Vector<TrinhDoNN> list = new Vector<>();
        QuanLiNhanSu.danhSachtrinhDoNN.values().stream()
                .forEach(x -> list.addElement(x));
        return new javax.swing.DefaultComboBoxModel<>(list);
    }

    /**
     * @param args the command line arguments
     */
    public static void callrun() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nhap_Sua_TTNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nhap_Sua_TTNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nhap_Sua_TTNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nhap_Sua_TTNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                obj = new Nhap_Sua_TTNV();
                obj.setVisible(true);
            }
        });
    }

    public static void callRun(Nhanvien nv) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                obj = new Nhap_Sua_TTNV(nv);
                obj.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btback;
    private javax.swing.JButton btcancel;
    private javax.swing.JButton btnext;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> txtchucvu;
    private javax.swing.JComboBox<String> txtchuyenmon;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtdienthoai;
    private javax.swing.JTextField txtemail;
    private javax.swing.JComboBox<String> txtgioitinh;
    private javax.swing.JTextField txtmatkhau;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JComboBox<String> txtphongbancongtac;
    private javax.swing.JComboBox<String> txtquanhuyen;
    private javax.swing.JComboBox<String> txttinh;
    private javax.swing.JComboBox<String> txttrinhdohocvan;
    private javax.swing.JComboBox<String> txttrinhdongoaingu;
    // End of variables declaration//GEN-END:variables

}
