/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.client.view;

import com.java.client.controller.ThoatController;
import com.java.model.Chucvu;
import com.java.model.Mucluong;
import com.java.model.dao.MucLuongDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.SortedMap;
import java.util.TreeMap;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MR.K
 */
public class QuanLiLuong extends javax.swing.JFrame {

    private static QuanLiLuong obj = null;
    public static SortedMap<String, Mucluong> danhSachMucLuong;
    public static SortedMap<String, Chucvu> danhSachChucVu = new TreeMap<>();

    /**
     * Creates new form quanliluong
     */
    public QuanLiLuong() {
        initComponents();
        if (QuanLiNhanSu.callRun().isVisible()) {
            this.setLocation(200, 100);
        } else {
            this.setLocationRelativeTo(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bang = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BtnEdit = new javax.swing.JButton();
        BtnDel = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        BtnQuit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SalaryPosition = new javax.swing.JMenu();
        SalaryTable = new javax.swing.JMenuItem();
        SalaryPos = new javax.swing.JMenuItem();
        RDmenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        paySlip = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salary Management");

        bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        bang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bang);

        BtnEdit.setText("Edit");
        BtnEdit.setEnabled(false);
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        BtnDel.setText("Delete");
        BtnDel.setEnabled(false);
        BtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelActionPerformed(evt);
            }
        });

        BtnAdd.setText("Add");
        BtnAdd.setEnabled(false);
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnQuit.setText("Quit");
        BtnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnQuit)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnAdd, BtnDel, BtnEdit, BtnQuit});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BtnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("Menu");

        SalaryPosition.setText("Payroll");

        SalaryTable.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        SalaryTable.setText("Salary table");
        SalaryTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryTableActionPerformed(evt);
            }
        });
        SalaryPosition.add(SalaryTable);

        SalaryPos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        SalaryPos.setText("Salary table of position");
        SalaryPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryPosActionPerformed(evt);
            }
        });
        SalaryPosition.add(SalaryPos);

        jMenu1.add(SalaryPosition);

        RDmenu.setText("Reward table-discipline");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Reward table");
        RDmenu.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText(" Discipline table");
        RDmenu.add(jMenuItem7);

        jMenu1.add(RDmenu);

        paySlip.setText("Make payslip");
        paySlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paySlipActionPerformed(evt);
            }
        });
        jMenu1.add(paySlip);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Exit the system");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalaryPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryPosActionPerformed
        this.bang.setModel(this.salaryTablePosModel());
        if ((QuanLiNhanSu.danhSachNhanVien.get(QuanLiNhanSu.username).getMaCv().equals("ADMIN")
                || QuanLiNhanSu.danhSachNhanVien.get(QuanLiNhanSu.username).getMaCv().equals("MGL"))) {
            //Check and change action
            if (this.BtnAdd.isEnabled()) {
                //goback from payslip
                if (!BtnAdd.isVisible()) {
                    BtnAdd.setVisible(true);
                    BtnEdit.setText("Edit");
                    BtnDel.setText("Delete");
                    removeActionList(BtnDel);
                    BtnDel.addActionListener((e) -> {
                        BtnDelActionPerformed(e);
                    });
                }
                this.BtnAdd.setEnabled(false);
                this.BtnDel.setEnabled(false);
                this.BtnEdit.setEnabled(false);
                this.BtnDel.setVisible(false);
                removeActionList(BtnEdit);
                BtnEdit.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        int row = bang.getSelectedRow();
                        NhapMucLuong_TheoChucVu.CallRun(bang.getValueAt(row, 0).toString(), bang.getValueAt(row, 2).toString());
                    }
                });
            }
        } else {
            this.BtnAdd.setVisible(false);
            this.BtnEdit.setVisible(false);
            this.BtnDel.setVisible(false);
        }
    }//GEN-LAST:event_SalaryPosActionPerformed

    private void SalaryTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryTableActionPerformed
        this.bang.setModel(this.salaryTableModel());
        //Check and change action
        if ((QuanLiNhanSu.danhSachNhanVien.get(QuanLiNhanSu.username).getMaCv().equals("AD")
                || QuanLiNhanSu.danhSachNhanVien.get(QuanLiNhanSu.username).getMaCv().equals("MGL"))) {
            if (!BtnAdd.isEnabled()) {
                BtnAdd.setEnabled(true);
                BtnDel.setVisible(true);
                BtnDel.setEnabled(false);
                BtnEdit.setEnabled(false);
                //goback from payslip
                if (!BtnAdd.isVisible()) {
                    BtnAdd.setVisible(true);
                    BtnEdit.setText("Edit");
                    BtnDel.setText("Delete");
                    removeActionList(BtnDel);
                    BtnDel.addActionListener((e) -> {
                        this.BtnDelActionPerformed(e);
                    });
                }
                removeActionList(BtnEdit);
                BtnEdit.addActionListener((e) -> {
                    this.BtnEditActionPerformed(e);
                });
            }
        } else {
            this.BtnAdd.setVisible(false);
            this.BtnEdit.setVisible(false);
            this.BtnDel.setVisible(false);
            this.RDmenu.setVisible(false);
            this.paySlip.setVisible(false);
        }
    }//GEN-LAST:event_SalaryTableActionPerformed

    public void refresh() {
        this.SalaryTableActionPerformed(null);
    }

    public void refreshPos() {
        this.SalaryPosActionPerformed(null);
    }

    private void removeActionList(JButton btn) {
        ActionListener[] al = btn.getActionListeners();
        for (ActionListener a : al) {
            btn.removeActionListener(a);
        }
    }

    private DefaultTableModel salaryTableModel() {
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Salary Level", "Amount"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        danhSachMucLuong.values().stream().forEach(luong -> model.addRow(new Object[]{luong.getMaML(),
            luong.getSoTien()
        }));
        return model;
    }

    private DefaultTableModel salaryTablePosModel() {
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Position ID", "Position Name", "Salary Level", "Amount"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        danhSachChucVu.values().stream()
                .forEach(cv -> model.addRow(new Object[]{cv.getMaCV(), cv.getTenCV(),
            cv.getMucluong().getMaML(), cv.getMucluong().getSoTien()
        }));
        return model;
    }
    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        // TODO add your handling code here:
        Them_MucLuong.callRun();
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuitActionPerformed
        // TODO add your handling code here:
        ThoatController.Thoat(this);
    }//GEN-LAST:event_BtnQuitActionPerformed

    private void bangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangMouseClicked
        // TODO add your handling code here:
        if (bang.getSelectedRow() != -1) {
            this.BtnEdit.setEnabled(true);
            this.BtnDel.setEnabled(true);
        }
    }//GEN-LAST:event_bangMouseClicked

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
        int row = this.bang.getSelectedRow();
        String value = this.bang.getValueAt(row, 0).toString();
        Sua_MucLuong.callRun(danhSachMucLuong.get(value));
    }//GEN-LAST:event_BtnEditActionPerformed

    private void BtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelActionPerformed
        // TODO add your handling code here:
        int row = bang.getSelectedRow();
        int choose = JOptionPane.showConfirmDialog(rootPane, "Do you want delete: " + bang.getValueAt(row, 0), "Confirm Dialog", JOptionPane.YES_NO_OPTION);
        if (choose == 0) {
            String key = bang.getValueAt(row, 0).toString();
            Mucluong ml = QuanLiLuong.danhSachMucLuong.remove(key);
            MucLuongDAO.deleteMucLuong(ml);
            ((DefaultTableModel) bang.getModel()).removeRow(row);
        }
    }//GEN-LAST:event_BtnDelActionPerformed

    private void paySlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paySlipActionPerformed
        // TODO add your handling code here:
        bang.setModel(QuanLiNhanSu.callRun().callModel());
        this.BtnAdd.setVisible(false);
        this.BtnEdit.setEnabled(false);
        this.BtnDel.setEnabled(false);
        this.BtnEdit.setText("View");
        this.BtnDel.setText("Make payslip");
        removeActionList(BtnEdit);
        removeActionList(BtnDel);
        this.BtnEdit.addActionListener(e -> {

        });
        this.BtnDel.addActionListener((e) -> {
            int row = bang.getSelectedRow();
            LapPhieuLuong.nv = QuanLiNhanSu.danhSachNhanVien.get(bang.getValueAt(row, 0));
            LapPhieuLuong.payer = QuanLiNhanSu.danhSachNhanVien.get(QuanLiNhanSu.username);
            LapPhieuLuong.callRun().setVisible(true);
        });
    }//GEN-LAST:event_paySlipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static QuanLiLuong callRun() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        if (obj == null) {
            obj = new QuanLiLuong();
        }
        return obj;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnDel;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnQuit;
    private javax.swing.JMenu RDmenu;
    private javax.swing.JMenuItem SalaryPos;
    private javax.swing.JMenu SalaryPosition;
    private javax.swing.JMenuItem SalaryTable;
    private javax.swing.JTable bang;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem paySlip;
    // End of variables declaration//GEN-END:variables
}
