/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.client.view;

import com.java.client.controller.ThoatController;
import com.java.config.LookConfig;
import com.java.model.Chucvu;
import com.java.model.Chuyenmon;
import com.java.model.Nhanvien;
import com.java.model.Phongban;
import com.java.model.Tinh;
import com.java.model.TrinhDoNN;
import com.java.model.dao.NhanvienDAO;
import java.util.Map;
import java.util.SortedMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macos
 */
public class QuanLiNhanSu extends javax.swing.JFrame {

    public static String username;
    public static QuanLiNhanSu obj = null;
    public static SortedMap<String, Nhanvien> danhSachNhanVien;
    public static Map<String, Chuyenmon> danhSachChuyenMon;
    public static Map<String, Phongban> danhSachPhongBan;
    public static Map<String, Tinh> Quequan;
    public static Map<String, TrinhDoNN> danhSachtrinhDoNN;

    /**
     * Creates new form QuanLiNhanSu
     */
    private QuanLiNhanSu() {
        initComponents();
        if (!username.equals("ADMIN")) {
            danhSachNhanVien.values().removeIf(x -> x.getMaNv().equals("ADMIN")); // Remove if none ADMIN
        }

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Bang = new javax.swing.JTable();
        BtnView = new javax.swing.JButton();
        BtnAdd = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        BtnDel = new javax.swing.JButton();
        Thoat = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        Action = new javax.swing.JMenu();
        DanhSachNv = new javax.swing.JMenuItem();
        KTKL = new javax.swing.JMenuItem();
        BangLuong = new javax.swing.JMenuItem();
        ThoatKhoiHeThong = new javax.swing.JMenuItem();
        trogiup = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Management System");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Bang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Bang);

        BtnView.setText("View");
        BtnView.setEnabled(false);
        BtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewActionPerformed(evt);
            }
        });

        BtnAdd.setText("Add");
        BtnAdd.setEnabled(false);
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnEdit.setText("Edit");
        BtnEdit.setEnabled(false);
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        BtnDel.setText("Delete");
        BtnDel.setEnabled(false);
        BtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelActionPerformed(evt);
            }
        });

        Thoat.setText("Quit");
        Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatActionPerformed(evt);
            }
        });

        Action.setText("Menu");

        DanhSachNv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        DanhSachNv.setText("View Employee List");
        DanhSachNv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DanhSachNvActionPerformed(evt);
            }
        });
        Action.add(DanhSachNv);

        KTKL.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        KTKL.setText("Reward and Discipline Tool");
        KTKL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KTKLActionPerformed(evt);
            }
        });
        Action.add(KTKL);

        BangLuong.setText("View Salary List");
        BangLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BangLuongActionPerformed(evt);
            }
        });
        Action.add(BangLuong);

        ThoatKhoiHeThong.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        ThoatKhoiHeThong.setText("Quit");
        ThoatKhoiHeThong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThoatKhoiHeThongActionPerformed(evt);
            }
        });
        Action.add(ThoatKhoiHeThong);

        Menu.add(Action);

        trogiup.setText("Help");
        Menu.add(trogiup);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnView, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BtnView)
                    .addComponent(BtnAdd)
                    .addComponent(BtnEdit)
                    .addComponent(BtnDel)
                    .addComponent(Thoat))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void callUpdate() {
        this.DanhSachNvActionPerformed(null);
    }
    public DefaultTableModel callModel(){
              DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID", "Name", "Address", "Mail", "Phone", "Position", "Dep No", "Edu", "Foregin Language"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        if (model.getRowCount() != 0) {
            model.setRowCount(0);
        }

        danhSachNhanVien.values().forEach((nv) -> {
            model.addRow(new Object[]{nv.getMaNv(), nv.getTenNv(), nv.getDc(),
                nv.getEmail(), nv.getDienThoai(),
                danhSachPhongBan.get(nv.getMaPb()).getDanhSachChucVu().get(nv.getMaCv()).getTenCV(),
                danhSachPhongBan.get(nv.getMaPb()).getTenPB(),
                danhSachChuyenMon.get(nv.getMaCM()).getTDHV(nv.getMaTDHV()).getTenTDHV(),
                danhSachtrinhDoNN.get(nv.getMaTDNN()).getTenTDNN()});
        });
        return model;
    }
    private void DanhSachNvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DanhSachNvActionPerformed
  
        Bang.setModel(this.callModel());
    }//GEN-LAST:event_DanhSachNvActionPerformed

    private void ThoatKhoiHeThongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatKhoiHeThongActionPerformed
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        int choose = JOptionPane.showConfirmDialog(rootPane, "Do you want quit?",
                "Confirmation", JOptionPane.YES_NO_OPTION);
        if (choose == 0) {
            this.dispose();
            DangNhap.callRun();
        }
    }//GEN-LAST:event_ThoatKhoiHeThongActionPerformed

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        Nhap_Sua_TTNV.callrun();
    }//GEN-LAST:event_BtnAddActionPerformed

    private void KTKLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KTKLActionPerformed
        // TODO add your handling code here:
        BangKTKL.callRun().setVisible(true);
    }//GEN-LAST:event_KTKLActionPerformed

    private void ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThoatActionPerformed
        ThoatController.Thoat(this);
    }//GEN-LAST:event_ThoatActionPerformed

    private void BtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelActionPerformed
        int row = Bang.getSelectedRow();
        int choose = JOptionPane.showConfirmDialog(rootPane, "Do you want delete: " + Bang.getValueAt(row, 2), "Confirm Dialog", JOptionPane.YES_NO_OPTION);
        if (choose == 0) {
            NhanvienDAO.deleteNhanVien(QuanLiNhanSu.danhSachNhanVien.get(Bang.getValueAt(row, 0)));
            danhSachNhanVien.remove(Bang.getValueAt(row, 0));
            ((DefaultTableModel) Bang.getModel()).removeRow(row);
        }
    }//GEN-LAST:event_BtnDelActionPerformed

    private void BtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewActionPerformed
        // TODO add your handling code here:
        int row = Bang.getSelectedRow();
        ThongTinNhanVien.nv = QuanLiNhanSu.danhSachNhanVien.get(Bang.getValueAt(row, 0));
        if (ThongTinNhanVien.nv != null) {
            ThongTinNhanVien.callRun();
        }
        this.setVisible(false);
    }//GEN-LAST:event_BtnViewActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        obj = null;
        ThoatController.Thoat(this);
    }//GEN-LAST:event_formWindowClosing

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        // TODO add your handling code here:
        int row = Bang.getSelectedRow();
        Nhap_Sua_TTNV.callRun(QuanLiNhanSu.danhSachNhanVien.get(Bang.getValueAt(row, 0)));
    }//GEN-LAST:event_BtnEditActionPerformed

    private void BangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BangMouseClicked
        // TODO add your handling code here:
        if(Bang.getSelectedRow() != -1){
            this.BtnView.setEnabled(true);
            this.BtnAdd.setEnabled(true);
            this.BtnEdit.setEnabled(true);
            this.BtnDel.setEnabled(true);
        }
    }//GEN-LAST:event_BangMouseClicked

    private void BangLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BangLuongActionPerformed
        // TODO add your handling code here:
        QuanLiLuong.callRun().setVisible(true);
    }//GEN-LAST:event_BangLuongActionPerformed

    public static QuanLiNhanSu callRun() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (LookConfig.LookAndFeel.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanSu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanSu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanSu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanSu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        if(obj == null){
            obj = new QuanLiNhanSu();
        }
        return obj;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Action;
    private javax.swing.JTable Bang;
    private javax.swing.JMenuItem BangLuong;
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnDel;
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnView;
    private javax.swing.JMenuItem DanhSachNv;
    private javax.swing.JMenuItem KTKL;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton Thoat;
    private javax.swing.JMenuItem ThoatKhoiHeThong;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu trogiup;
    // End of variables declaration//GEN-END:variables
}
