/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.client.view;

import com.java.client.controller.DateController;
import com.java.client.controller.ThoatController;
import com.java.model.Lilichcongtac;
import com.java.model.Nhanvien;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows 8
 */
public class ThongTinNhanVien extends javax.swing.JFrame {

    public static Nhanvien nv = null;

    /**
     * Creates new form ThongTinNhanVien
     */
    public ThongTinNhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        ttNoiCongTac = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ttNhanvien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ttNoiCongtac = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ttThanNhan = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin nhân viên");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ttNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"FullName:", nv.getTenNv()},
                {"ID:", nv.getMaNv()},
                {"Address:", nv.getDc()},
                {"Gender:", nv.isPhai()?"Nam":"Nu"},
                {"Birthday:", nv.getNgSinh()},
                {"Position:", QuanLiNhanSu.danhSachPhongBan.get(nv.getMaPb()).getChucvu(nv.getMaCv()).getTenCV()},
                {"Department:", QuanLiNhanSu.danhSachPhongBan.get(nv.getMaPb()).getTenPB()},
                {"Phone:", nv.getDienThoai()},
                {"Email:", nv.getEmail()},
                {"Education:", QuanLiNhanSu.danhSachChuyenMon.get(nv.getMaCM()).getTDHV(nv.getMaTDHV())},
                {"Technique:", QuanLiNhanSu.danhSachChuyenMon.get(nv.getMaCM()).getTenCM()},
                {"Foreign Language:", QuanLiNhanSu.danhSachtrinhDoNN.get(nv.getMaTDNN()).getTenTDNN()},
                {"Password (only 3 character of password):", nv.getPassword().substring(0, 3)}
            },
            new String [] {
                "My Infomation", ""
            }
        ){
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false ,false ,false ,false ,false ,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ttNhanvien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        ttNoiCongTac.addTab("Information", jPanel1);

        ttNoiCongtac.setModel(createLiLichCongTac());
        jScrollPane1.setViewportView(ttNoiCongtac);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        ttNoiCongTac.addTab("Go on bussiness", jPanel2);

        ttThanNhan.setModel(createDanhSachThanNhan());
        jScrollPane3.setViewportView(ttThanNhan);
        if (ttThanNhan.getColumnModel().getColumnCount() > 0) {
            ttThanNhan.getColumnModel().getColumn(0).setHeaderValue("Relatives Information");
            ttThanNhan.getColumnModel().getColumn(1).setHeaderValue("");
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        ttNoiCongTac.addTab("Relatives", jPanel3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ttNoiCongTac)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ttNoiCongTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (QuanLiNhanSu.obj != null) {
            QuanLiNhanSu.obj.setVisible(true);
            this.dispose();
        } else {
            ThoatController.Thoat(this);
        }
    }//GEN-LAST:event_formWindowClosing
    public DefaultTableModel createLiLichCongTac() {

        DefaultTableModel model = new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Bussiness", "Address", "Date"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        ArrayList arrRow = new ArrayList();
        for(Lilichcongtac congtac:nv.getDanhSachCongTac()){
            arrRow.add(congtac.getTenNoiCT());
            arrRow.add(congtac.getDC());
            arrRow.add(congtac.getThgian());
            
            model.addRow(arrRow.toArray());
            arrRow.clear();
        };
        return model;
    }

    public DefaultTableModel createDanhSachThanNhan() {
        if (nv.getDanhSachThanNhan().containsKey("Wife")) {
            return new javax.swing.table.DefaultTableModel(
                    new Object[][]{
                        {"Father Name:", nv.getDanhSachThanNhan().get("Father").getTenTN()},
                        {"Address:", nv.getDanhSachThanNhan().get("Father").getDC()},
                        {"Birthday:", nv.getDanhSachThanNhan().get("Father").getNgSinh()},
                        {"Mother Name:", nv.getDanhSachThanNhan().get("Mother").getTenTN()},
                        {"Address:", nv.getDanhSachThanNhan().get("Mother").getDC()},
                        {"Birthday:", nv.getDanhSachThanNhan().get("Mother").getNgSinh()},
                        {"Husband/Wife Name:", nv.getDanhSachThanNhan().get("Wife").getTenTN()},
                        {"Address:", nv.getDanhSachThanNhan().get("Wife").getDC()},
                        {"Daybirth:", nv.getDanhSachThanNhan().get("Wife").getNgSinh()}
                    },
                    new String[]{
                        "Relatives Information", ""
                    }
            ) {
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
        } else if (nv.getDanhSachThanNhan().containsKey("Husband")) {

            return new javax.swing.table.DefaultTableModel(
                    new Object[][]{
                        {"Father Name:", nv.getDanhSachThanNhan().get("Father").getTenTN()},
                        {"Address:", nv.getDanhSachThanNhan().get("Father").getDC()},
                        {"Birthday:", nv.getDanhSachThanNhan().get("Father").getNgSinh()},
                        {"Mother Name:", nv.getDanhSachThanNhan().get("Mother").getTenTN()},
                        {"Address:", nv.getDanhSachThanNhan().get("Mother").getDC()},
                        {"Birthday:", nv.getDanhSachThanNhan().get("Mother").getNgSinh()},
                        {"Husband/Wife Name:", nv.getDanhSachThanNhan().get("Husband").getTenTN()},
                        {"Address:", nv.getDanhSachThanNhan().get("Husband").getDC()},
                        {"Daybirth:", nv.getDanhSachThanNhan().get("Husband").getNgSinh()}

                    },
                    new String[]{
                        "Relatives Information", ""
                    }
            ) {
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
        }
        return new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {"Father Name:", nv.getDanhSachThanNhan().get("Father").getTenTN()},
                    {"Address:", nv.getDanhSachThanNhan().get("Father").getDC()},
                    {"Birthday:", nv.getDanhSachThanNhan().get("Father").getNgSinh()},
                    {"Mother Name:", nv.getDanhSachThanNhan().get("Mother").getTenTN()},
                    {"Address:", nv.getDanhSachThanNhan().get("Mother").getDC()},
                    {"Birthday:", nv.getDanhSachThanNhan().get("Mother").getNgSinh()}
                },
                new String[]{
                    "Relatives Information", ""
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
    }

    /**
     * @param args the command line arguments
     */
    public static void callRun() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable ttNhanvien;
    private javax.swing.JTabbedPane ttNoiCongTac;
    private javax.swing.JTable ttNoiCongtac;
    private javax.swing.JTable ttThanNhan;
    // End of variables declaration//GEN-END:variables
}
